world_place = ['Tokoyo', 'Paris', 'London', 'Rome']
print(world_place)
print(sorted(world_place))
print(world_place)
print(sorted(world_place, reverse=True))
print(world_place)
world_place.reverse()
print(world_place)
world_place.reverse()
print(world_place)
world_place.sort()
print(world_place)
world_place.sort(reverse=True)
print(world_place)
